# Generated by Django 4.0 on 2021-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.CharField(blank=True, default='n/a', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
