# Generated by Django 4.0.3 on 2023-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_bio_alter_useraccount_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='github',
            field=models.URLField(default='n/a'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='instagram',
            field=models.URLField(default='n/a'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='linkedin',
            field=models.URLField(default='n/a'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='twitter',
            field=models.URLField(default='n/a'),
        ),
    ]
