# Generated by Django 4.0.3 on 2023-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_caption_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
